### ISSUE TITLE
Large .bin files seem to be appended to existing file when resuming

### ISSUE THREAD

**Issue by NikolausC** [hippie68/ftpdump#13]
I'm attempting to dump Horizon Zero Dawn Complete Edition which has three large bin files, roughly 8-12GB each. When resuming these downloads (interrupted due to trophy issue mentioned in #8), all other files which have already been downloaded are skipped over just fine, but for these three it seems to download the whole contents of the files again. So after the first attempt, one of the files is 7.59GB, then when I re-run with resume it goes to 16.18GB. I'm running it on macOS.

I've been using your reccomended ps4-ftp bin, rather than the one built into GoldHEN.

**Comment by hippie68** [comment]
Bug confirmed and fixed, thank you for reporting!
The bug was in the FTP server code, for the updated version see here: https://github.com/hippie68/ps4-ftp/releases.

I'm afraid the three files that already have wrong data appended have to be deleted, as the resume process, realizing the local files are larger than those on the server, would simply skip them.

**Comment by NikolausC** [comment]
Thanks so much! Can confirm it's working now :)
